# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/tools"
      - "/v2/awsv1shim"
    groups:
      aws-sdk-go-v1:
        patterns:
          - "github.com/aws/aws-sdk-go"
      aws-sdk-go-v2:
        patterns:
          - "github.com/aws/aws-sdk-go-v2"
          - "github.com/aws/aws-sdk-go-v2/*"
      opentelemetry:
        patterns:
          - "go.opentelemetry.io/otel"
          - "go.opentelemetry.io/contrib/*"
    ignore:
      # aws/smithy-go should only be updated via aws/aws-sdk-go-v2
      - dependency-name: "github.com/aws/smithy-go"
      - dependency-name: "golang.org/x/tools"
    schedule:
      interval: "daily"
